# Generated by Django 2.1.2 on 2018-10-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(default='Mi dirección de envío', max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(max_length=5)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=4)),
                ('floor', models.CharField(blank=True, max_length=3)),
                ('door', models.CharField(blank=True, max_length=3)),
                ('is_company', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='album', max_length=50)),
                ('author', models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Mi información bancaria', max_length=50)),
                ('account', models.CharField(blank=True, max_length=20)),
                ('month', models.CharField(blank=True, max_length=2)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('security_code', models.CharField(blank=True, max_length=3)),
                ('is_company', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='', max_length=50)),
                ('company', models.CharField(blank=True, default='', max_length=50)),
                ('education', models.CharField(blank=True, default='', max_length=50)),
                ('extract', models.TextField(blank=True, default=' ')),
                ('collaborator_image', models.ImageField(blank=True, default='photos/user_profile.jpg', upload_to='photos')),
                ('cropping', image_cropping.fields.ImageRatioField('collaborator_image', '390x450', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='mi empresa', max_length=50)),
                ('slug', models.CharField(blank=True, default=' ', max_length=100)),
                ('description', models.CharField(blank=True, default=' ', max_length=100)),
                ('phone', models.CharField(blank=True, default='000000000', max_length=9)),
                ('web', models.CharField(blank=True, max_length=50)),
                ('company_image', models.ImageField(blank=True, default='photos/default_company_image.jpg', upload_to='photos')),
                ('cropping', image_cropping.fields.ImageRatioField('company_image', '160x160', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.BooleanField(default=False)),
                ('image', models.ImageField(default='/image.jpg', upload_to='photos')),
                ('description', models.CharField(blank=True, max_length=20)),
                ('alt', models.CharField(blank=True, max_length=20)),
                ('album', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthylifeapp.Album')),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=9)),
                ('profile_image', models.ImageField(blank=True, default='photos/user_profile.jpg', upload_to='photos')),
                ('cropping', image_cropping.fields.ImageRatioField('profile_image', '390x450', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
