# Generated by Django 2.1.2 on 2018-10-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(blank=True, default=' ', max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('privacity', models.IntegerField(blank=True, choices=[(1, 'Público'), (2, 'Privado')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Deporte'), (2, 'Nutrición'), (3, 'Salud')], default=1)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('notes', models.CharField(blank=True, default='', max_length=250)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
