# Generated by Django 2.1.2 on 2018-10-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthylifeapp', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Activo'), (2, 'Inactivo')], default=2)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, default=' ', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField()),
                ('award_type', models.IntegerField(choices=[(1, 'Porcentaje'), (2, 'Cantidad')], default=2)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthylifeapp.Album')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_category_author', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='awards.Category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awards.Category'),
        ),
        migrations.AddField(
            model_name='award',
            name='shop_objects',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='award',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Beneficiario', to=settings.AUTH_USER_MODEL),
        ),
    ]
